### ISSUE TITLE
dotnet tool install -g fails with no package found

### ISSUE THREAD

**Issue by chrissmithptml** [endjin/dotnet-adr#102]
When following the instructions for the installation of dotnet-adr,, the readme states just run
`dotnet tool install -g adr`

However, doing so bombs with the following error

**error NU1103: Unable to find a stable package adr with version (>= 0.0.0)**
**error NU1103:   - Found 4 version(s) in nuget.org [ Nearest version: 0.1.0-preview.36 ]**
**The tool package could not be restored.**

This appears to be because there is no 1.0.0+ version of the nuget package.

Looking at the build status on the repo, this package is not being actively built / deployed to nuget.  Happy to help to get this going if you need contributors.

Cheers

**Comment by HowardvanRooijen** [comment]
You can use

`dotnet tool install --global adr --version 0.1.0-preview.36`

Let me know if that works.

**Comment by chrissmithptml** [comment]
That totally works, cheers.  Are you guys intending on publishing a 1.x.x version to nuget?  If you need a hand, I'm happy to help out, get it rockin' in github actions in a PR, if that helps you guys.

Let me know

C

**Comment by HowardvanRooijen** [comment]
I need to circle back to the project - there are a number of improvements I want to back port from other CLI tools I've been subsequently using System.CommandLine.

It does already have a fully CI/CD pipeline - we have over [30 OSS project over 7+ orgs](https://endjin.com/what-we-do/open-source/) and at the moment we use Azure DevOps via standard set of reusable templates - [Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub](https://github.com/endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub) to automate all that.

Give me a week or so and I'll see if I can make some time to make those updates. Nothing should stop you using the tool though, I've been using it in this state since I published it!

Would love feedback / suggestions if you spend some time using it.

Thanks!

**Comment by chrissmithptml** [comment]
Take your time.  I know how busy we all can be, and with so many projects on the go, you're likely busy on all kinds of levels.

I took the component for a test drive, and thus far it looks great.  I'll let you know if I find anything for improvements, but looks like you've nailed it.
